language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_HOST
    - secure: "qvuKJ+cRaOTK+3bTQ+Qpt/jV++EU45iC3mCf0k+DjR5PuyG7o7xyZSm1WiPGf8D+r1AhiH9Vkx2sCI3HeGePeDF6kgE7kJmThVjqcazAeBKCa7soHdVb44G3rPG65utOmFxACPLfPKaf3wm9spOnZVlLT7Cx601Ciu15tCqsN8WXF9kUdYqHUnzzjqCSZrydXXagkLu1d86xhZ7E3/qb4XJJaIeZjwge0TU+0JcnqWCjqos6y/pYl8sEJxyLjzaTMTmKm5YpwZjEMF2ORoIje11hs+wToIeCSRyFrVCTqmepPuSDR4Ox7Q/lwQ9RI+Vofnq6ee3zKqOOqcUqiPi697gYNos47M5FI7WmFv+qKMglQuwgmazl3L8cf8Zd0eFgpUJAn96Ox/4Rf5RT6WxwLw0cTvTZ2DTiYCFk3MSuFXXSZMiJQ5WSjgJnA0Xk6+BQ+gyzOz/FGK2F3e4YQa3DlTZ3rXmCkPGqBCqq16FdLdeuh7SvT3vqbe+n4odjaS97ym72AXrdhYIX9GKkebKjl6oFrHusgIi4KzDEGVWIycG8DyVrbH9W3Ra1jp42s3btBqcgPnI0s+9vPYmcSd9GX38m4JEcHdmR1LfkUD0rR06NXnui7guJU3gk21+n0XEPUgJh1ttqAKB/3NtBL33T60bk0Lz9VcQW1534XU6L7e0="

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build.sh

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
