language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # FTP_USER
    - secure: "nOEvCgeOHWOtsrHJbD/H5ytsTrec2cCYfTpiodkRrSAYCR5iVINJvccYpn03Ymd3BkW9hrIQE++z+eDA3I51UdW1HFb2r2wlsfcQOjDFb1nVvNEc6JMIQNAZ59HTSE1aasovmXdaikTVp/7GFYP7TlVKjP/yqAd3zSisWLeyKQUlWCNQqHFafAM1tXi0/vXfU3H3YND05OgsH0k24AJdXEhXDLaF0eh/JgfZkiemUZQS7RHnlo/Xj4c7EIWg84u9idgwcoQ9ry1OzWA9OgujQWFyvF4b+p95LGQxz8rkSi6yVuubHaUVVhC6G685CVY7Z0rEWQEtBTLUT5DjRgZYIUePSLu8KpY7ZsaQYipmgJ4LxFM09KFXU2dBAKnslDON6FErzuUE3hq718t0ZtobMSy+RPiqYCGOXwTlTHx2vrVXaeuncdZbPaAlV6G0sRKEeKK22LiC/OQjQLPrWjsPoOUnjHBuk9SS/xGW09XOg93DjhsmN35uYFe4ix6LbjprCRIH/PUaEct/hr7zfBWQTUNgf7grH4Ywow6+Y82czFsO/JQxCmByBJtXghYbMKbapO+WKcTWw0H+vW0E5JNuJpitWOw3StXAWsQvGIp2z7q3Xi8sxPvNZOMcNY65TFA3ks796C5SQSwFacHIcHsz5ZckFhgZJu6joKAG08zxVuA="
    # FTP_PASSWORD
    - secure: "wm07SRdml6Xw3Wml4d8t/62zfkL+EULEGcr+P995TIqElF4LrbU3mzOb+VI7IioUQ3IRKgXuJ9iy9Jk/ZW6WO/tGOkkTpjuWSmzvKISWuzsZIrxWUTScLZyQbmWxbQcwfMq0z6/1dV+ROnqbZnygTLYv3TNbgJzZAF0GOVd+JJCofSM21nXU9kyo5NGuvXQvNOO9gtS/i+Mv+wnHOADngcVCG3VPRDDewHcJH/T8O3cTLGIICHAQKcYyFj67Bp1PnBocLsiNNT9AZfkcjyEOcrE65fELa6guLGsODLCxs244q/B+4KZKHkQfeLdrJYejttGSW+aKSoua9BEDoW5frN6l4xRsA20f67CU9T7CuuHTwQuLn/Im8rbqHW3zHEHXcxb7dGC/tzBcxWFQbnRgClVhbuRX8Yr/TYZToBF6SXaEtmAiOxiiz8YxXIJyzBQLuTWCXJT0C/caAIj6YV/O9TNcN99hfOGYwme+i2op1bFVTj1Kzl4dVNTa74BFQHF8IpTQsmydgCj7rHdYKKo+rDsSiQwQu6zhusfzYQ0J8S0yODGd0MOmpeFaUvBHhp+0uOSbxW0WtiyLlyL5wvn0+fni90sO+N9GmMmKsbUrn4tZpes5QPmDgqTddjvd2Qy9y/V+RAHgW+9Kw4bybn7Bgavfyxt2jC40a7jrt4HzSXo="
    # FTP_URL
    - secure: "Nn5n+ZKTdNe5xaYIC9tkHZEHg6vphmKo23o6+q9heHrHCkb1fwl0bfv94A3izGeKyLNrxxRXhNujCybmkcNXSChjbr9PkJnPRdMwM2rQb4Q9Jzw+5xaOP8A2K5gJwY+nMJU9F5GHcz5KIgnOLAyIDU2HrVDrAKPgBnk/sagA2vCZBidJlh5wnTynxe431dhJ/HEtkIeDdE/XvD3u/VDXQdS4XnmLPw3MSJra9coQnjFRCxE7cHi0xebfDLzJ0PKGW7w4DIBnHBvyHEqw0cMywQk3VxZvVV2WzdkBi14pWqEE4LjhhXaGfFdSsrpTu2zTElifxX1HuK2Uxe/aebAaokrL/3cUazH1LPhjpI7ljmp4jDoXsmGXIu+0MgzrmVv9q5em/j4TrSWrq3MUtMF/lLBBsh7WaAdtY9qVF5KV73N6BYkT8oOn5rPqQoRUdwrtq80wK7Y6UVCgAOzDguUSWh8oCftzai1VbwI31cbYsyqNYM9d0I5/BYZK/MHGnbqaZF+VqKNvNqOUD9/eZbLvjIbsMXEnM5Xw7S0ZrKb1q2c7sWTL0HUlEmrLG00S47tojwzQHyRaEb1MfhHJbxrho9cCW4Cw+yu3snH5HvGwi9MI+1S9zKRUUwW0QvHHuQCQGfAkmlfqjLIt9nknQ6fSAEYoYqcmIUl6dctChN1mv8o="

arch:
  artifacts:
    - fluid-artifacts.tar.gz
    - libliri-artifacts.tar.gz
  packages:
    - qbs
    - qt5-declarative
    - qt5-tools
    - karchive
    - xorg-server-xvfb
    - desktop-file-utils
    - appstream
    - flatpak
    #- clazy-git
  script:
    #- export CLAZY_CHECKS="level1"
    - qbs-setup-toolchains --detect
    - qbs-setup-qt /usr/bin/qmake-qt5 qt5
    - qbs config profiles.qt5.baseProfile ${CC}
    - eval `dbus-launch --sh-syntax` && xvfb-run -a -s "-screen 0 800x600x24" qbs -d build -j $(nproc) profile:qt5

script:
  - "curl -s https://raw.githubusercontent.com/lirios/repotools/develop/travis/docker-travis.sh | bash"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
