language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

arch:
  artifacts:
    - fluid-artifacts.tar.gz
    - libliri-artifacts.tar.gz
  packages:
    - qbs
    - qt5-tools
    - karchive
    - xorg-server-xvfb
    - desktop-file-utils
    - appstream
    - flatpak
    #- clazy-git
  script:
    #- export CLAZY_CHECKS="level1"
    - qbs-setup-toolchains --detect
    - qbs-setup-qt /usr/bin/qmake-qt5 qt5
    - qbs config profiles.qt5.baseProfile ${CC}
    - eval `dbus-launch --sh-syntax` && xvfb-run -a -s "-screen 0 800x600x24" qbs -d build -j $(nproc) profile:qt5

script:
  - "curl -s https://raw.githubusercontent.com/lirios/repotools/develop/travis/docker-travis.sh | bash"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
